sudo: false
language: node_js
branches:
  only:
    - master
notifications:
  email: false
install:
  - npm install
before_script:
  - git config --global user.email $GH_EMAIL
  - git config --global user.name $GH_USERNAME
  - git remote set-url origin https://$GH_TOKEN@github.com/rowanhogan/wikipadia.git
  - npm install -g gulp
  - npm install
script:
  - npm run deploy
